INSERT INTO VENTADOMICILIO_OWN.POS_SERVICES
	(ID, SERVICE_NAME, SERVICE_DESCRIPTION,IS_EXTERNAL_CALL) 
	VALUES (2, 'EQUIFAX', 'ID provider', 'Y')
;

CREATE TABLE VENTADOMICILIO_OWN.FV29_CLIENTE_DATOS (
	DOC_NUMERO 		VARCHAR2(10) NOT NULL,
	EXISTE 			VARCHAR2(1) NOT NULL,
	ID_TRANSACTION 	VARCHAR2(25) NULL,
	DOC_TIPO 		VARCHAR2(10) NULL,
	DOC_SERIE 		VARCHAR2(10) NULL,
	DOC_ESTADO 		VARCHAR2(10) NULL,
	DOC_MOTIVO 		VARCHAR2(20) NULL,
	NOMBRES 		VARCHAR2(60) NULL,
	APATERNO 		VARCHAR2(30) NULL,
 	AMATERNO 		VARCHAR2(30) NULL,
	NACIONALIDAD 	VARCHAR2(20) NULL,
	SEXO 			VARCHAR2(1) NULL,
	ECIVIL 			VARCHAR2(10) NULL, 
	FNACIMIENTO 	VARCHAR2(8) NULL,
	FDEFUNCION 		VARCHAR2(8) NULL,
	FMATRIMONIO 	VARCHAR2(8) NULL,
	FECHA_CONSULTA_DATOS TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	CONSTRAINT FV29_CLIENTE_DATOS_PK PRIMARY KEY (DOC_NUMERO)
);