INSERT INTO VENTADOMICILIO_OWN.POS_SERVICES
	(ID, SERVICE_NAME, SERVICE_DESCRIPTION,IS_EXTERNAL_CALL) 
	VALUES (2, 'EQUIFAX', 'ID provider', 'Y')
;

CREATE TABLE VENTADOMICILIO_OWN.FV29_CLIENTE_DATOS (
	DOC_NUMERO VARCHAR2(10),
	EXISTE VARCHAR2(1),
	ID_TRANSACTION VARCHAR2(25),
	DOC_TIPO VARCHAR2(10),
	DOC_SERIE VARCHAR2(10),
	DOC_ESTADO VARCHAR2(10),
	DOC_MOTIVO VARCHAR2(20),
	NOMBRES VARCHAR2(60),
	APATERNO VARCHAR2(30),
	AMATERNO VARCHAR2(30),
	NACIONALIDAD VARCHAR2(20),
	SEXO VARCHAR2(1),
	ECIVIL VARCHAR2(10),
	FNACIMIENTO VARCHAR2(8),
	FDEFUNCION VARCHAR2(8),
	FMATRIMONIO VARCHAR2(8),
	FECHA_CONSULTA_DATOS TIMESTAMP DEFAULT SYSTIMESTAMP ,
	FAULT_STRING VARCHAR2(10),
	FAULT_DETAIL VARCHAR2(50),
	CONSTRAINT FV29_CLIENTE_DATOS_PK PRIMARY KEY (DOC_NUMERO),
	CONSTRAINT SYS_C0031998 CHECK ("DOC_NUMERO" IS NOT NULL),
	CONSTRAINT SYS_C0032000 CHECK ("FECHA_CONSULTA_DATOS" IS NOT NULL)
);
CREATE UNIQUE INDEX FV29_CLIENTE_DATOS_PK ON VENTADOMICILIO_OWN.FV29_CLIENTE_DATOS (DOC_NUMERO);